[project]
name = "mydjangox"
version = "1.0.0"
description = "My Django project template. Inspired by Will Vincent's DjangoX."
readme = "README.md"
authors = [
    {name = "Stuart Maxwell", email = "stuart@amanzi.nz"},
]
license = {text = "MIT"}
requires-python = "==3.14.*"
dependencies = [
  "django~=6.1.0",
  "environs[django]~=15.0",
  "gunicorn~=25.3",
  "rich~=15.0",
  "whitenoise~=6.12",
  "django-crispy-forms~=2.6",
  "crispy-bootstrap5~=2026.3",
]

[dependency-groups]
dev = [
    "django-debug-toolbar~=6.3",
    "pytest~=9.0",
    "pytest-django~=4.12",
]

[tool.pdm]
distribution = false

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings_testing"
python_files = "tests.py test_*.py *_tests.py"

[tool.djangofmt]
line-length = 120
indent-width = 2
profile = "django"
html-void-self-closing = "never"
preserve-unquoted-attrs = false
