line-length = 120
target-version = "py314"

[lint]
select = ["ALL"]
ignore = [
  "G004",   # Logging statement uses f-string
  "D203",   # 1 blank line required before class docstring
  "D213",   # multi-line-summary-second-line
  "TD003",  # Missing issue link on the line following this TODO
  "FIX002", # Line contains TODO, consider resolving the issue
  "TD002",  # Missing author in TODO
  "S308",   # suspicious-mark-safe-usage
  "PGH003", # Use specific rule codes when ignoring type issues
  "COM812", # Trailing comma missing
  "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
]

[lint.per-file-ignores]
# "test*" = ["ALL"]
"**/migrations/*" = ["ALL"]

[lint.extend-per-file-ignores]
"test*" = ["ANN001", "ANN002", "ANN202", "ANN003", "ANN201", "ANN206", "S101", "S106", "PLC0415", "PLR2004", "T201", "PT011", "SLF001"]

[lint.pydocstyle]
convention = "google" # Accepts: "google", "numpy", or "pep257".
